In [2]:
import numpy as np
import gym
import random

In [3]:
env = gym.make("Taxi-v2")
env = gym.make("MountainCar-v0")
env.render()

In [5]:
action_size = env.action_space.n
print("Action size:", action_size)

state_size = env.observation_space
print("State space", state_size)

print(env.observation_space.low)
print(env.observation_space.high)

Action size: 3
State space Box(2,)
[-1.2  -0.07]
[ 0.6   0.07]


In [6]:
def stateToIndex(x):
    
    if -1.2 <= x <= -1.1:
        return 0
    elif -1.1 <= x <= -1.0:
        return 1
    elif -1.0 <= x <= -0.9:
        return 2
    elif -0.9 <= x <= -0.8:
        return 3
    elif -0.8 <= x <= -0.7:
        return 4
    elif -0.7 <= x <= -0.6:
        return 5
    elif -0.6 <= x <= -0.5:
        return 6
    elif -0.5 <= x <= -0.4:
        return 7
    elif -0.4 <= x <= -0.3:
        return 8
    elif -0.3 <= x <= -0.2:
        return 9
    elif -0.2 <= x <= -0.1:
        return 10
    elif -0.1 <= x <= 0.0:
        return 11
    elif 0.0 <= x <= 0.1:
        return 12
    elif 0.1 <= x <= 0.2:
        return 13
    elif 0.2 <= x <= 0.3:
        return 14
    elif 0.3 <= x <= 0.4:
        return 15
    elif 0.4 <= x <= 0.5:
        return 16
    elif 0.5 <= x <= 0.6:
        return 17

state = env.reset()
print(state)
print(stateToIndex(state[0]))

[-0.46784398  0.        ]
7


In [7]:
qtable = np.zeros((18, action_size))
print(qtable)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [11]:
total_episodes = 2        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 2               # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob


In [15]:
rewards = []

for episode in range(total_episodes):
    # State is an int describing the placement of the taxi
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    if episode % 1000 == 0:
        pass
        # print("Average score at episode " + str(episode) + ": " + str(sum(rewards)/total_episodes))
    
    for step in range(max_steps):
        
        curr_place = qtable[stateToIndex(state[0]),:]
        
        exp_exp_tradeoff = random.uniform(0, 1)
        
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(curr_place)
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        print(state, action, new_state, reward)
        
        qtable[stateToIndex(state[0])][action] = 3
        
        # qtable[curr_place], action] + learning_rate * (reward + gamma * np.max(curr_place], :]) - curr_place(state[0])], action])
        
        total_rewards += reward
        
        state = new_state
        
        if done:
            break
    
    episode += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

print(qtable)
# print("Score over time: " + str(sum(rewards)/total_episodes))


[-0.5339496  0.       ] 1 [ -5.33871984e-01   7.76187257e-05] -1.0
[ -5.33871984e-01   7.76187257e-05] 0 [-0.53471733 -0.00084534] -1.0
[-0.52261642  0.        ] 2 [-0.52162379  0.00099263] -1.0
[-0.52162379  0.00099263] 1 [-0.52064597  0.00097782] -1.0
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [13]:
env.reset()


for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    # print("****************************************************")
    # print("EPISODE ", episode)

    for step in range(max_steps):
        # env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[stateToIndex(state[0]),:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            break
        state = new_state
env.render(close=True)
print("Score over time: " + str(sum(rewards)/5))

Score over time: -400000.0


In [4]:
env.render(close=True)